
[project]
name = "vocana"
version = "0.2.1"
description = ""
authors = [
    {name = "l1shen", email = "lishen1635@gmail.com"},
]
dependencies = [
    "paho-mqtt>=1.6.1",
]
requires-python = ">=3.7"
license = {text = "MIT"}

[tool.pdm.scripts]
publish_vocana = { shell = "./scripts/publish_vocana.sh" }
publish_executor = { shell = "./scripts/publish_executor.sh" }

[tool.pdm.dev-dependencies]
dev = [
    "amqtt>=0.11.0b1",
    "setuptools>=68.0.0",
]
[tool.setuptools.packages.find]
where = ["src"]