[project]
name = "oocana"
version = "0.6.0"
description = "python implement of oocana to give a context for oocana block"
dependencies = ["paho-mqtt>=2"]
requires-python = ">=3.9"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

