name: pr check

on:
  pull_request:
    paths:
      - "!**.md"
      - "!.github/workflows/**"
      - ".github/workflows/pr.yml"
      - "**.py"
      - "pyproject.toml"
      - "pdm.lock"

jobs:
  pr-check:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4
      # TODO: 在 self-hosted 环境，需要在全局环境安装 pdm，使用这个 action，第一次可以正常安装，但是后续会报错，查出来的 python 路径找不到，需要在全局环境安装 pdm
      # self-hosted runner already has pdm installed
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: setup pdm
        uses: pdm-project/setup-pdm@v4
      - name: install dependencies
        run: pdm install
      - name: build
        run: pdm build