name: pr check

on:
  pull_request:
    paths:
      - "!**.md"
      - "!.github/workflows/**"
      - ".github/workflows/pr.yml"
      - "**.py"
      - "pyproject.toml"
      - "pdm.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pdm
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: install dependencies
        run: pdm install
      - name: build
        run: pdm build
      - name: static check
        run: pdm check
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./test/package.json
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: https://npm.pkg.github.com/
          cache: "pnpm"
      - name: install
        run: |-
          cd test
          pnpm start broker &
          pdm executor &
          pnpm start