name: pr check

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  pr-check:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4
      # TODO: 让 self-hosted 环境，支持重复安装 pdm
      # pdm self-hosted already has pdm installed
      # - name: setup pdm
      #   uses: pdm-project/setup-pdm@v4
      - name: install dependencies
        run: pdm install
      - name: build
        run: pdm build