name: pr check

on:
  push:
    paths-ignore:
      - "**.md"
jobs:
  pr-check:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4
      # pdm self-hosted already has pdm installed
      # - name: setup pdm
      #   uses: pdm-project/setup-pdm@v4
      - name: install dependencies
        run: pdm install
      - name: build
        run: pdm build