name: publish

on:
  push:
    tags:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write 

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.result.outputs.command }}
    steps:
      - if: startsWith(github.ref, 'refs/tags/oocana-python-executor')
        run: |-
          echo "command=publish_executor" >> $GITHUB_OUTPUT
        id: step1
      - if: startsWith(github.ref, 'refs/tags/oocana')
        run: |-
          echo "command=publish_oocana" >> $GITHUB_OUTPUT
        id: step2
      - id: result
        run: |
          if [ -n "${{ steps.step1.outputs.command }}" ]; then
            echo "command=${{ steps.step1.outputs.command }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ steps.step2.outputs.command }}" ]; then
            echo "command=${{ steps.step2.outputs.command }}" >> $GITHUB_OUTPUT
          else
            exit 1
          fi
  publish:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pdm
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: install dependencies
        run: pdm install
      - name: publish to pypi
        run: pdm ${{ needs.vars.outputs.command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}