name: publish

on:
  push:
    tags:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-executor:
    if: startsWith(github.ref, 'refs/tags/@oomol/python-executor')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pdm
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: install dependencies
        run: pdm install
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://npm.pkg.github.com/
      - name: build an publish to npm
        run: pdm publish_executor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-sdk:
    if: startsWith(github.ref, 'refs/tags/@oomol/python-sdk')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pdm
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: install dependencies
        run: pdm install
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com/"
      - name: build an publish to npm
        run: pdm publish_oocana
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}