name: publish

on:
  push:
    tags:
      - "**"
jobs:
  publish-executor:
    if: startsWith(github.ref, 'refs/tags/@oomol/executor')
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: install dependencies
        run: pdm install
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          scope: "@vocana"
          registry-url: https://npm.pkg.github.com/
      - name: build an publish to npm
        run: pdm publish_executor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VOCANA_PUBLISH_TOKEN }}
  publish-sdk:
    if: startsWith(github.ref, 'refs/tags/@oomol/python-sdk')
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: install dependencies
        run: pdm install
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          scope: "@vocana"
          registry-url: "https://npm.pkg.github.com/"
      - name: build an publish to npm
        run: pdm publish_vocana
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VOCANA_PUBLISH_TOKEN }}