name: publish

on:
  push:
    tags:
      - "**"
jobs:
  publish-executor:
    if: startsWith(github.ref, 'refs/tags/@vocana/executor')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          scope: "@vocana"
          registry-url: https://npm.pkg.github.com/
          token: ${{ secrets.VOCANA_PUBLISH_TOKEN }}
      - name: build an publish to npm
        run: pdm publish_executor
  publish-sdk:
    if: startsWith(github.ref, 'refs/tags/@vocana/sdk-python')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pdm
        uses: pdm-project/setup-pdm@v4
      - name: install dependencies
        run: pdm install
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          scope: "@vocana"
          registry-url: "https://npm.pkg.github.com/"
          token: ${{ secrets.VOCANA_PUBLISH_TOKEN }}
      - name: build an publish to npm
        run: pdm publish_vocana